---
- name: Setup Satellite User and Install Katello Agent
  hosts: all 
  gather_facts: no
  become: yes  # Use sudo for tasks that require elevated privileges
  
  tasks:
    - name: Create sudoers file
      file:
        path: /etc/sudoers.d/satelliteusr
        state: absent

    - name: Create sudoers file
      file:
        path: /etc/sudoers.d/satelliteusr
        state: touch

    - name: Create the satellite user
      user:
        name: satelliteusr
        state: present

    - name: Add sudoers entry for satellite user
      lineinfile:
        path: /etc/sudoers.d/satelliteusr
        line: "satelliteusr  ALL=(ALL) NOPASSWD: /var/tmp/foreman-ssh-cmd*/script, /bin/true"
        state: present

