---
- name: Upgrade Ubuntu Release
  hosts: 192.168.154.131  # Define your target group in your inventory
  become: yes  # Use sudo to perform operations that require root privileges
  tasks:
    - name: Ensure the system is up to date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install update-manager-core if not already installed
      apt:
        name: update-manager-core
        state: present

    - name: Check for available upgrades
      command: do-release-upgrade -n -m server -f DistUpgradeViewNonInteractive
      register: upgrade_result
      changed_when: "'No new release found' not in upgrade_result.stdout"

    - name: Reboot the system if required
      reboot:
        msg: "Rebooting after release upgrade"
      when: "'Reboot is required' in upgrade_result.stdout"

    - name: Upgrade the system if a new release is found
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      when: "'New release is available' in upgrade_result.stdout"
      register: final_upgrade_result

    - name: Reboot again if required after upgrade
      reboot:
        msg: "Rebooting after final release upgrade"
      when: "'Reboot is required' in final_upgrade_result.stdout"

    - name: Clean up obsolete packages
      apt:
        autoremove: yes
        purge: yes

